# Generated by Django 2.2.6 on 2020-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200220_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(verbose_name='Want to Publish Now?(Otherwise It will save as draft)'),
        ),
    ]
